"""empty message

Revision ID: 4c36ff50980a
Revises: 
Create Date: 2022-04-10 10:39:05.128917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c36ff50980a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashSenha', sa.Text(), nullable=True),
    sa.Column('loginSocial', sa.Boolean(), nullable=True),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('docNum', sa.String(length=20), nullable=False),
    sa.Column('empresaAtiva', sa.Boolean(), nullable=True),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docNum')
    )
    op.create_table('empresaLogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formaPagamento', sa.String(length=256), nullable=True),
    sa.Column('pagamentoRealizado', sa.Boolean(), nullable=True),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tempoAtendimento', sa.Integer(), nullable=False),
    sa.Column('intervaloAtendimento', sa.Integer(), nullable=False),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('nomeUsuario', sa.String(length=24), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashSenha', sa.Text(), nullable=True),
    sa.Column('loginSocial', sa.Boolean(), nullable=True),
    sa.Column('administrador', sa.Boolean(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nomeUsuario')
    )
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color1', sa.String(length=7), nullable=True),
    sa.Column('color2', sa.String(length=7), nullable=True),
    sa.Column('color3', sa.String(length=7), nullable=True),
    sa.Column('maximoTarefas', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendadoPara', sa.DateTime(), nullable=False),
    sa.Column('terminoPrevistoPara', sa.DateTime(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('dataHoraCriacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agenda.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarefa')
    op.drop_table('agenda')
    op.drop_table('usuario')
    op.drop_table('grupo')
    op.drop_table('servico')
    op.drop_table('pagamento')
    op.drop_table('empresaLogo')
    op.drop_table('empresa')
    op.drop_table('cliente')
    # ### end Alembic commands ###
